language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - IMAGINE_VERSION=^1
  - IMAGINE_VERSION=dev-develop

before_script:
  - composer require imagine/imagine:${IMAGINE_VERSION}

matrix:
  allow_failures:
    - env: IMAGINE_VERSION=dev-develop
