language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - IMAGINE_VERSION=^1
  - IMAGINE_VERSION=dev-develop

before_script:
  - sudo apt-get -y --reinstall install imagemagick
  - pecl channel-update pecl.php.net
  - yes | pecl install imagick
  - composer require imagine/imagine:${IMAGINE_VERSION} --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit

matrix:
  allow_failures:
    - env: IMAGINE_VERSION=dev-develop
