language: php

php:
  - 5.4
  - 5.5
  - 5.6 

env:
  - IMAGINE_VERSION=~0.6
  - IMAGINE_VERSION=dev-develop

before_script:
  - composer require imagine/imagine:${IMAGINE_VERSION}

matrix:
  allow_failures:
    - env: IMAGINE_VERSION=dev-develop
